LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := mpg123_shared
LOCAL_MODULE_FILENAME := libmpg123
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libmpg123.so
include $(PREBUILT_SHARED_LIBRARY)
